# Generated by Django 3.2.5 on 2022-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'favorite_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopTagTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'shop_tag_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopTb',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_desc', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tel_num', models.CharField(max_length=11)),
                ('parking_info', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('reg_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'shop_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagTb',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
                ('hit_cnt', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tag_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTb',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(db_column='pass', max_length=255)),
                ('phone_num', models.CharField(max_length=15, null=True)),
                ('reg_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_tb',
                'managed': False,
            },
        ),
    ]
