# Generated by Django 3.2.5 on 2022-05-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
    ]
