# Generated by Django 3.2.5 on 2022-05-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_employees_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='COUNTRIES',
        ),
        migrations.AlterModelTable(
            name='departments',
            table='DEPARTMENTS',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='EMPLOYEES',
        ),
        migrations.AlterModelTable(
            name='jobhistory',
            table='JOB_HISTORY',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='JOBS',
        ),
        migrations.AlterModelTable(
            name='locations',
            table='LOCATIONS',
        ),
        migrations.AlterModelTable(
            name='regions',
            table='REGIONS',
        ),
    ]
